rules:
  bem-depth: 1
  border-zero: 0
  brace-style: 1
  class-name-format:
    - 1
    - convention: hyphenatedbem
  clean-import-paths: 1
  empty-args: 0
  empty-line-between-blocks: 1
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline: 1
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format: 1
  hex-length: 1
  hex-notation: 1
  id-name-format: 1
  indentation: 1
  leading-zero: 1
  mixin-name-format: 1
  mixins-before-declarations: 0
  nesting-depth: 0
  no-color-keywords: 1
  no-color-literals: 0
  no-css-comments: 1
  no-debug: 0
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 1
  no-important: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties:
    - 1
    - extra-properties: [osx-font-smoothing]
  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: 1
  no-trailing-zero: 1
  no-transition-all: 0
  no-url-protocols: 0
  no-vendor-prefixes: 1
  no-warn: 0
  one-declaration-per-line: 1
  placeholder-in-extend: 1
  placeholder-name-format: 1
  property-sort-order: 1
  property-units: 0
  quotes: 1
  shorthand-values: 1
  single-line-per-selector: 1
  space-after-bang: 1
  space-after-colon: 1
  space-after-comma: 1
  space-around-operator: 1
  space-before-bang: 1
  space-before-brace: 1
  space-before-colon: 1
  space-between-parens: 1
  trailing-semicolon: 1
  url-quotes: 1
  variable-for-property: 0
  variable-name-format: 1
  zero-unit: 1
